let arr=[{
    img:"https://www.bigbasket.com/media/uploads/p/s/10000069_20-fresho-capsicum-green.jpg",
    tag:"Fresho",
    name:"Capsicum - Green (Loose)",
    price:"MRP:Rs.41",
    description:"Standard Delivery: Tomorrow 3:00PM - 7:30PM",
},
{
    img:"https://www.bigbasket.com/media/uploads/p/s/10000071_14-fresho-carrot-orange.jpg",
    tag:"Fresho",
    name:"Carrot - Orange (Loose)",
    price:"MRP:Rs 18.75",
    description:"Standard Delivery: Tomorrow 3:00PM - 7:30PM",
},
{
    img:"https://www.bigbasket.com/media/uploads/p/s/10000097_19-fresho-coriander-leaves.jpg",
    tag:"Fresho",
    name:"Coriander Leaves",
    price:"MRP:Rs 8.50",
    description:"Standard Delivery: Tomorrow 3:00PM - 7:30PM",
},
{
    img:"https://www.bigbasket.com/media/uploads/p/s/10000102_17-fresho-cucumber.jpg",
    tag:"Fresho",
    name:"Cucumber (Loose)",
    price:"MRP:Rs 18.50",
    description:"Standard Delivery: Tomorrow 3:00PM - 7:30PM",
},
{
    img:"https://www.bigbasket.com/media/uploads/p/s/10000144_13-fresho-ladies-finger.jpg",
    tag:"Fresho",
    name:"Ladies' Fingers (Loose)",
    price:"MRP:Rs 19.75",
    description:"Standard Delivery: Tomorrow 3:00PM - 7:30PM",
},
]